productpage:
  namespace: student17-bookinfo-uat
  image: ghcr.io/pspapleng/bookinfo-productpage
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8083
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.uat.opsta.net
  path: "/student17/productpage(/|$)(.*)"
  serviceType: ClusterIP
    